version: '3'

services:
  mysqldb:
      command: ["--default-authentication-plugin=mysql_native_password"]
      image: mysql
      volumes:
        - ./database/mysql-data:/var/lib/mysql
        - ./database/mysql-init-files:/docker-entrypoint-initdb.d
      restart: always
      networks:
        - backend
      environment:
        - MYSQL_ROOT_PASSWORD=12345678
        - MYSQL_DATABASE=shorturl
        - MYSQL_USER=testuser
        - MYSQL_PASSWORD=12345678
      ports:
        - "3306:3306"
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
      expose:
      - 3306  
  api:
    image: short-url-express-app
    build: ./api/
    networks:
      - backend
    links:
      - mysqldb:mysqldb  
    ports:
      - "3000:3000"
    volumes:
        - ./api/:/usr/src/app  
           
networks:
  backend:
    driver: "bridge"
